"""empty message

Revision ID: 14a2d42a1a55
Revises: e3c100b953c1
Create Date: 2024-05-06 05:42:24.847930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a2d42a1a55'
down_revision = 'e3c100b953c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_userid', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['user.id'], name=op.f('fk_review_agent_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_userid'], ['user.userid'], name=op.f('fk_review_author_userid_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
