"""empty message

Revision ID: 129d0c6c7ef3
Revises: b93d12e58691
Create Date: 2024-05-14 15:53:20.826073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129d0c6c7ef3'
down_revision = 'b93d12e58691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
