"""empty message

Revision ID: 9b3d375e043c
Revises: 2c323f4bf518
Create Date: 2024-05-12 01:18:04.416977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3d375e043c'
down_revision = '2c323f4bf518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
