"""empty message

Revision ID: 597977bb5ca0
Revises: 2145b91a7f0b
Create Date: 2024-05-13 13:29:48.147461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597977bb5ca0'
down_revision = '2145b91a7f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['propertyListing.id'], name=op.f('fk_property_image_property_id_propertyListing')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_image'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_image')
    # ### end Alembic commands ###
