"""empty message

Revision ID: e008970fb208
Revises: 1372820c56fe
Create Date: 2024-05-11 02:42:28.969417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e008970fb208'
down_revision = '1372820c56fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('seller', 'buyer', 'agent', 'admin', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('userid', name=op.f('uq_user_userid'))
    )
    op.create_table('propertyListing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('floorSize', sa.Integer(), nullable=False),
    sa.Column('floorLevel', sa.Enum('low', 'medium', 'high', name='floorlevel'), nullable=False),
    sa.Column('propertyType', sa.Enum('hdb', 'condo', 'apartment', 'studio', name='propertytype'), nullable=False),
    sa.Column('furnishing', sa.Enum('partially_furnished', 'fully_furnished', 'not_furnished', name='furnishing'), nullable=False),
    sa.Column('builtYear', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('view_counts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['user.id'], name=op.f('fk_propertyListing_agent_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['user.userid'], name=op.f('fk_propertyListing_client_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_propertyListing'))
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_userid', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['user.id'], name=op.f('fk_review_agent_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_userid'], ['user.userid'], name=op.f('fk_review_author_userid_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_userid', sa.String(length=32), nullable=False),
    sa.Column('propertyListing_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['propertyListing_id'], ['propertyListing.id'], name=op.f('fk_favourite_propertyListing_id_propertyListing'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_userid'], ['user.userid'], name=op.f('fk_favourite_user_userid_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favourite'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite')
    op.drop_table('review')
    op.drop_table('propertyListing')
    op.drop_table('user')
    # ### end Alembic commands ###
