"""empty message

Revision ID: 202d56ab3795
Revises: 8ac3b3473ab9
Create Date: 2024-05-07 04:24:17.145329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202d56ab3795'
down_revision = '8ac3b3473ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propertyListing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('view_counts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('shortlist_count', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_propertyListing_client_id_user'), 'user', ['client_id'], ['userid'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_propertyListing_agent_id_user'), 'user', ['agent_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propertyListing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_propertyListing_agent_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_propertyListing_client_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('shortlist_count')
        batch_op.drop_column('view_counts')
        batch_op.drop_column('client_id')
        batch_op.drop_column('agent_id')
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
