"""empty message

Revision ID: a462e2da0e56
Revises: 919a0ea8fee1
Create Date: 2024-05-07 04:38:52.778341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a462e2da0e56'
down_revision = '919a0ea8fee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propertyListing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortlist_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propertyListing', schema=None) as batch_op:
        batch_op.drop_column('shortlist_count')

    # ### end Alembic commands ###
