"""empty message

Revision ID: c59d576bb101
Revises: 14a2d42a1a55
Create Date: 2024-05-06 20:46:50.972186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59d576bb101'
down_revision = '14a2d42a1a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_userid', sa.String(length=32), nullable=False),
    sa.Column('propertyListing_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['propertyListing_id'], ['propertyListing.id'], name=op.f('fk_favourite_propertyListing_id_propertyListing'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_userid'], ['user.userid'], name=op.f('fk_favourite_user_userid_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favourite'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite')
    # ### end Alembic commands ###
