"""empty message

Revision ID: 018b7c0919c5
Revises: 7ddf202d5444
Create Date: 2024-05-05 23:17:25.420309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018b7c0919c5'
down_revision = '7ddf202d5444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propertyListing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('propertyListing', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
