"""empty message

Revision ID: 6e233a418ded
Revises: 
Create Date: 2024-05-04 23:57:16.694084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e233a418ded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propertyListing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('floorSize', sa.Integer(), nullable=False),
    sa.Column('floorLevel', sa.Enum('low', 'medium', 'high', name='floorlevel'), nullable=False),
    sa.Column('propertyType', sa.Enum('hdb', 'condo', 'apartment', 'studio', name='propertytype'), nullable=False),
    sa.Column('furnishing', sa.Enum('partially_furnished', 'fully_furnished', 'not_furnished', name='furnishing'), nullable=False),
    sa.Column('builtYear', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('seller', 'buyer', 'agent', 'admin', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('propertyListing')
    # ### end Alembic commands ###
